export const weatherActionTypes={
    FETCH_DATA_START:"FETCH_DATA_START",
    FETCH_DATA_SUCCESS:"FETCH_DATA_SUCCESS",
    FETCH_DATA_FAILURE:"FETCH_DATA_FAILURE",
    RESET_WEATHER_DATA:"RESET_WEATHER_DATA"
}